# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-11 21:39
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Richness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stateab', models.CharField(max_length=254)),
                ('statenm', models.CharField(max_length=254)),
                ('countynm', models.CharField(max_length=254)),
                ('plot_idn', models.BigIntegerField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('elev', models.FloatField()),
                ('invyr', models.BigIntegerField()),
                ('area', models.BigIntegerField()),
                ('s', models.BigIntegerField()),
                ('tree_dens', models.BigIntegerField()),
                ('plot_agb', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Spplist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stateab', models.CharField(max_length=254)),
                ('statenm', models.CharField(max_length=254)),
                ('countynm', models.CharField(max_length=254)),
                ('plot_idn', models.FloatField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('elev', models.FloatField()),
                ('spcd', models.BigIntegerField()),
                ('genus', models.CharField(max_length=254)),
                ('species', models.CharField(max_length=254)),
                ('variety', models.CharField(max_length=254)),
                ('subspecies', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='TreeLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study', models.CharField(max_length=254)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('plot_id', models.BigIntegerField()),
                ('plotarea_m', models.BigIntegerField()),
                ('year', models.BigIntegerField()),
                ('full_speci', models.CharField(max_length=254)),
                ('tree_id', models.FloatField()),
                ('dbhcm', models.FloatField()),
                ('abundance', models.BigIntegerField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
