# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-21 17:01
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoFIA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SppNProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statecd', models.BigIntegerField()),
                ('stateab', models.CharField(max_length=254)),
                ('statenm', models.CharField(max_length=254)),
                ('countycd', models.BigIntegerField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('elev', models.FloatField()),
                ('plot', models.BigIntegerField()),
                ('plot_id', models.CharField(max_length=254)),
                ('plotidn', models.BigIntegerField()),
                ('period', models.BigIntegerField()),
                ('n_inventor', models.BigIntegerField()),
                ('sppn', models.BigIntegerField()),
                ('mean_treed', models.FloatField()),
                ('mai_basala', models.FloatField()),
                ('mai_biomas', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='TreesPerYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statenm', models.CharField(max_length=254)),
                ('statecd', models.BigIntegerField()),
                ('stateab', models.CharField(max_length=254)),
                ('countycd', models.BigIntegerField()),
                ('plot', models.BigIntegerField()),
                ('plot_id', models.CharField(max_length=254)),
                ('plotidn', models.BigIntegerField()),
                ('subp', models.BigIntegerField()),
                ('n_inventor', models.BigIntegerField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('elev', models.FloatField()),
                ('invyr', models.BigIntegerField()),
                ('tree', models.FloatField()),
                ('spcd', models.BigIntegerField()),
                ('accepted_n', models.CharField(max_length=254)),
                ('family', models.CharField(max_length=254)),
                ('dia', models.FloatField()),
                ('ht_m', models.CharField(max_length=254)),
                ('ba_m2', models.FloatField()),
                ('biomass_kg', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
