# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-11 22:39
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoFIA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='USGrid100km',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('xmin', models.FloatField()),
                ('xmax', models.FloatField()),
                ('ymin', models.FloatField()),
                ('ymax', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(db_index=True, srid=4326)),
            ],
        ),
        migrations.AlterField(
            model_name='richness',
            name='countynm',
            field=models.CharField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='richness',
            name='elev',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='richness',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(db_index=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='richness',
            name='plot_agb',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='richness',
            name='plot_idn',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='richness',
            name='stateab',
            field=models.CharField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='richness',
            name='statenm',
            field=models.CharField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='spplist',
            name='countynm',
            field=models.CharField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='spplist',
            name='elev',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='spplist',
            name='genus',
            field=models.CharField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='spplist',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(db_index=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='spplist',
            name='plot_idn',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='spplist',
            name='species',
            field=models.CharField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='spplist',
            name='stateab',
            field=models.CharField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='spplist',
            name='statenm',
            field=models.CharField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='spplist',
            name='subspecies',
            field=models.CharField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='spplist',
            name='variety',
            field=models.CharField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='treelevel',
            name='abundance',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='treelevel',
            name='full_speci',
            field=models.CharField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='treelevel',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(db_index=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='treelevel',
            name='plot_id',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='treelevel',
            name='study',
            field=models.CharField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='treelevel',
            name='tree_id',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='treelevel',
            name='year',
            field=models.BigIntegerField(db_index=True),
        ),
    ]
