# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-02 11:28
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoFIA', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usgrid100km',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(db_index=True, srid=4326),
        ),
    ]
