# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-21 18:36
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoFIA', '0002_sppnproduct_treesperyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiomassGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spp_group', models.CharField(db_index=True, max_length=254)),
                ('spcd', models.CharField(db_index=True, max_length=254)),
                ('family', models.CharField(db_index=True, max_length=254)),
                ('newgenus', models.CharField(db_index=True, max_length=254)),
                ('newspecies', models.CharField(db_index=True, max_length=254)),
                ('usfs_wd', models.CharField(db_index=True, max_length=254)),
                ('chave_wd', models.CharField(db_index=True, max_length=254)),
                ('chavewd_level', models.CharField(db_index=True, max_length=254)),
                ('code', models.CharField(db_index=True, max_length=254)),
                ('group', models.CharField(db_index=True, max_length=254)),
                ('taxa', models.CharField(db_index=True, max_length=254)),
                ('b_0', models.CharField(db_index=True, max_length=254)),
                ('b_1', models.CharField(db_index=True, max_length=254)),
                ('mindbh', models.CharField(db_index=True, max_length=254)),
                ('maxdbh', models.CharField(db_index=True, max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='sppnproduct',
            name='countycd',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='sppnproduct',
            name='elev',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='sppnproduct',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(db_index=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='sppnproduct',
            name='lat',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='sppnproduct',
            name='lon',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='sppnproduct',
            name='n_inventor',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='sppnproduct',
            name='period',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='sppnproduct',
            name='plot',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='sppnproduct',
            name='plot_id',
            field=models.CharField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='sppnproduct',
            name='plotidn',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='sppnproduct',
            name='stateab',
            field=models.CharField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='sppnproduct',
            name='statecd',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='sppnproduct',
            name='statenm',
            field=models.CharField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='treesperyear',
            name='accepted_n',
            field=models.CharField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='treesperyear',
            name='ba_m2',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='treesperyear',
            name='biomass_kg',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='treesperyear',
            name='dia',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='treesperyear',
            name='elev',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='treesperyear',
            name='family',
            field=models.CharField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='treesperyear',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(db_index=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='treesperyear',
            name='ht_m',
            field=models.CharField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='treesperyear',
            name='invyr',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='treesperyear',
            name='lat',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='treesperyear',
            name='lon',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='treesperyear',
            name='n_inventor',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='treesperyear',
            name='plot_id',
            field=models.CharField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='treesperyear',
            name='plotidn',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='treesperyear',
            name='spcd',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='treesperyear',
            name='subp',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='treesperyear',
            name='tree',
            field=models.FloatField(db_index=True),
        ),
    ]
