# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-02 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoFIA', '0003_auto_20170902_1130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usgrid100km',
            options={'managed': False},
        ),
    ]
