# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-03 07:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoFIA', '0004_auto_20170902_1152'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usgrid100km',
            table='mesh"."us100km',
        ),
    ]
