# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-03 07:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoFIA', '0005_auto_20170903_0747'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usgrid100km',
            options={},
        ),
    ]
