# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-03 07:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoFIA', '0006_auto_20170903_0748'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usgrid100km',
            options={'managed': False},
        ),
    ]
